### DISCUSSION TITLE
Implementing FullScreen Functionality In these project.

### DISCUSSION THREAD

**Discussion by iammaulik1** [PierfrancescoSoffritti/android-youtube-player#975] [General]
I tried to implement it by help of your source code but i am continuously getting errors. so , can anybody give me code with fullscreen implementation in it. and add its functionality inside Quick Start code which is provided by owner.

**Comment by PierfrancescoSoffritti** [comment]
You can have a look in the sample app, it contains a complete example.

**Reply by iammaulik1** [reply]
yes , i had implemented by it . but i am not able to do it by myself. so can you help me and send me its code after generating it ?

**Reply by PierfrancescoSoffritti** [reply]
I am not sure what you mean, the code is [here](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples).

**Comment by martinezdputrajulo** [comment]
hi, i'm currently using the version `11.1.0` of your library. is there any way to toggle the fullscreen from the IFrame in this version? I tried to update it to `12.0.0` but when I try to build my project it gives me an error.

```
Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
```

Take note that the project I'm working on is an existing app that contains a lot of legacy codes, thus upgrading common libraries (such as `core-ktx`) versions are not easy

**Comment by PierfrancescoSoffritti** [comment]
Interesting, I would like to find out why this issue is happening. Would it be possible to share your project with me? if not, could you share you're gradle files? I would like to replicate the issue on my end.

**Comment by martinezdputrajulo** [comment]
sharing the project is not possible because it's a private project owned by the company that I'm currently working for. sharing all the gradle files wouldn't be a good option either as it is a multi-module project with over 20++ modules. so here are some of the things that I can share you about the project:

**AS Studio Version**
```
Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023
Runtime version: 11.0.15+0-b2043.56-9505619 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    com.jetbrains.edu (2023.1-2022.1-1267)
    tarn.gradle.dependencies (1.6.2)
    com.intellij.lang.jsgraphql (3.3.0)
    String Manipulation (9.5.0)
```

**Top level gradle.build**
```Gradle
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        maven { url "https://plugins.gradle.org/m2/" }
        google()
        mavenCentral()
    }

    dependencies {
        classpath BuildDependency.gradleBuildTools
        classpath BuildDependency.gradleIoTools
        classpath BuildDependency.gradlePlugin
        classpath BuildDependency.jacoco
        classpath BuildDependency.gmsService // Google Services plugin
        classpath BuildDependency.firebase // Performance Monitoring plugin
        classpath BuildDependency.crashlytics
    }
}

plugins {
    id 'org.jetbrains.kotlin.android' version '1.6.21' apply false
    ... other classified plugins
}
... other classified fields
```

**BuildDependency.kt**
```Kotlin
object BuildDependency {
    const val gradleBuildTools = "com.android.tools.build:gradle:7.3.1"
    const val gradleIoTools = "io.fabric.tools:gradle:1.31.1"
    const val gradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21"
    const val jacoco = "org.jacoco:org.jacoco.core:0.8.8"
    const val gmsService = "com.google.gms:google-services:4.3.15"
    const val firebase = "com.google.firebase:perf-plugin:1.4.1"
    const val crashlytics = "com.google.firebase:firebase-crashlytics-gradle:2.7.1"
}
```

**Gradle JDK**: `11.0.15`

**Lib Dependencies Versions (uses `.toml`)**
```toml
androidJunit = "1.1.5"
androidxActivity = "1.2.0-alpha03"
androidxAppCompat = "1.2.0"
androidxArchitectureTestCore = "2.1.0"
androidxBrowser = "1.3.0"
androidxCardView = "1.0.0"
androidxConstraintLayout = "2.1.4"
androidxCoreKtx = "1.8.0"
androidxEmoji = "1.1.0"
androidxFuture = "1.1.0"
androidxGridLayout = "1.0.0"
androidxLegacySupport = "1.0.0"
androidxLifecycle = "2.4.0"
androidxLifecycleCompiler = "2.0.0"
androidxLifecycleExtension = "2.2.0"
androidxLifecycleRuntime = "2.0.0"
androidxLifecycleRuntimeKtx = "2.2.0-alpha01"
androidxLiveData = "2.5.1"
androidxNavigation = "2.3.3"
androidxRecyclerView = "1.2.1"
androidxVectorAnimated = "1.0.0"
androidxViewModel = "2.5.1"
androidxWindow = "1.0.0"
androidxWorkRuntimeKtx = "2.7.1"
apache = "3.4"
appsFlyer = "5.4.0"
blurry = "4.0.1"
blurView = "version-2.0.2"
bluSdk = "1.31.0-nr"
butterKnife = "10.0.0"
camerax = "1.2.1"
chucker = "3.5.2"
circularProgressBar = "3.1.0"
codec = "1.10"
coroutines = "1.3.1"
customTabs = "3.0.3"
dagger = "2.40.5"
datadog = "1.8.1"
desugar = "1.1.5"
encryption = "1.4.2"
fastAdapter = "3.3.1"
firebase = "17.5.0"
firebaseConfig = "21.0.1"
firebaseCrashlytics = "18.2.1"
firebaseMessaging = "22.0.0"
firebasePerformance = "20.0.2"
glide = "4.9.0"
gms = "17.0.0"
gmsAds = "18.0.1"
gmsAnalytics = "18.0.2"
gmsFaceDetection = "17.1.0"
gmsMapsUtil = "0.4.3"
gmsPlaces = "2.6.0"
gmsSignIn = "17.0.0"
googleIntegrity = "1.0.1"
googleMaterial = "1.4.0"
googlePlay = "1.8.0"
gson = "2.8.6"
innovatricsCommons = "1.12.1"
innovatricsDispatch = "1.0.0"
innovatricsFace = "4.11.1"
installReferrer = "1.0"
jackson = "1.22.0"
javaxAnnotationGlassFish = "10.0-b28"
javaxAnnotationJsr = "1.0"
joda = "2.9.9"
json = "20180813"
junit = "4.12"
kotlin = "1.6.21"
liveDataTesting = "1.2.0"
lottie = "3.4.0"
materialIntro = "2.2.0"
mockito = "3.3.3"
mockitoKotlin = "1.5.0"
mockitoKotlinAlternate = "4.0.0"
mockk = "1.12.4"
mockWebServer = "3.9.0"
moengage = "12.2.02"
moengageInApp = "6.2.0"
moengageInbox = "2.0.0"
moengagePushAmp = "4.0.0"
moengagePushAmpPlus = "5.0.0"
moengageRichNotification = "4.3.1"
okHttp = "3.10.0"
orchestrator = "1.2.0"
pageIndicator = "v.1.0.3"
picasso = "2.71828"
pinEntryEditText = "2.0.6"
powermock = "2.0.0"
retrofit = "2.6.0"
retrofitRxJavaAdapter = "2.4.0"
robolectric = "3.8"
room = "2.3.0"
rootBeer = "0.1.0"
rxAndroid = "2.0.2"
rxBinding = "2.1.1"
rxJava = "2.1.9"
rxKotlin = "2.2.0"
rxRelay = "2.0.0"
sdp = "1.0.5"
seon = "5.0.2"
skydoves = "1.4.7"
toggleView = "1.1.0"
truth = "1.0"
uglyToolTip = "v1.0.6-beta"
uxCam = "3.6.0"
youtubePlayer = "11.1.0"
zendesk = "2.9.0"
```
